DROP TABLE IF EXISTS logs;
DROP TABLE IF EXISTS klines;
DROP TABLE IF EXISTS orderbooks;
DROP TABLE IF EXISTS trades;
DROP TABLE IF EXISTS tickers;
DROP TABLE IF EXISTS product_exchange;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS exchanges;
