export default {
  exchanges: {
    joins: {},
    fields: [
      { field: 'id', as: 'pk_exchange_id' },
      { field: 'name', as: 'name' },
      { field: 'label', as: 'label' },
      { field: 'created', as: 'exchange_created' },
    ],
  },
  products: {
    joins: {
      exchanges: { type: 'INNER', field: 'exchange_id' },
    },
    fields: [
      { field: 'id', as: 'pk_product_id' },
      { field: 'pair', as: 'pair' },
      { field: 'base', as: 'base' },
      { field: 'quote', as: 'quote' },
      { field: 'trading', as: 'trading' },
      { field: 'margin', as: 'margin' },
      { field: 'iceberg', as: 'iceberg' },
      { field: 'oco', as: 'oco' },
      { field: 'spot_trading', as: 'spot_trading' },
      { field: 'base_min', as: 'base_min' },
      { field: 'base_max', as: 'base_max' },
      { field: 'quote_min', as: 'quote_min' },
      { field: 'quote_max', as: 'quote_max' },
      { field: 'created', as: 'product_created' },
      { field: 'exchange_id', as: 'exchange_id' },
    ],
  },
  tickers: {
    joins: {
      products: { type: 'RIGHT', field: 'product_id' },
      exchanges: { type: 'RIGHT', field: 'exchange_id' },
    },
    fields: [
      { field: 'id', as: 'pk_ticker_id' },
      { field: 'server_time', as: 'server_time' },
      { field: 'sequence', as: 'sequence' },
      { field: 'price', as: 'price' },
      { field: 'size', as: 'size' },
      { field: 'bid', as: 'bid' },
      { field: 'ask', as: 'ask' },
      { field: 'volume', as: 'volume' },
      { field: 'created', as: 'ticker_created' },
      { field: 'product_id', as: 'product_id' },
      { field: 'exchange_id', as: 'exchange_id' },
    ],
  },
  trades: {
    joins: {
      products: { type: 'RIGHT', field: 'product_id' },
      exchanges: { type: 'RIGHT', field: 'exchange_id' },
    },
    fields: [
      { field: 'id', as: 'pk_trade_id' },
      { field: 'server_time', as: 'server_time' },
      { field: 'sequence', as: 'sequence' },
      { field: 'price', as: 'price' },
      { field: 'size', as: 'size' },
      { field: 'quote_size', as: 'quote_size' },
      { field: 'side', as: 'side' },
      { field: 'best_match', as: 'best_match' },
      { field: 'created', as: 'trade_created' },
      { field: 'product_id', as: 'product_id' },
      { field: 'exchange_id', as: 'exchange_id' },
    ],
  },
  klines: {
    joins: {
      products: { type: 'RIGHT', field: 'product_id' },
      exchanges: { type: 'RIGHT', field: 'exchange_id' },
    },
    fields: [
      { field: 'id', as: 'pk_kline_id' },
      { field: 'server_time', as: 'server_time' },
      { field: 'low', as: 'low' },
      { field: 'high', as: 'high' },
      { field: 'open', as: 'open' },
      { field: 'close', as: 'close' },
      { field: 'amount', as: 'amount' },
      { field: 'volume', as: 'volume' },
      { field: 'period', as: 'period' },
      { field: 'created', as: 'kline_created' },
      { field: 'product_id', as: 'product_id' },
      { field: 'exchange_id', as: 'exchange_id' },
    ],
  },
}
